version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{- title .Os }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: leap
    homepage: https://github.com/ajilk/tools
    repository:
      owner: ajilk
      name: tools
      token: "{{ .Env.GITHUB_TOKEN }}"
